<?php
/**
 * This file is part of the Magento 2 Shipping module of DPD Nederland B.V.
 *
 * Copyright (C) 2019  DPD Nederland B.V.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

use DpdConnect\ShippingHyva\ViewModel\CheckoutConfig;
use Hyva\Theme\Model\ViewModelRegistry;

/** @var ViewModelRegistry $viewModels */

/** @var CheckoutConfig $checkoutConfigViewModel */
$checkoutConfigViewModel = $viewModels->require(CheckoutConfig::class);

$checkoutConfig = $checkoutConfigViewModel->getConfig();
?>

<div x-data="initDpdShipping()" x-on:click.window="handleWindowClick($event)">
    <div id="dpd-connect-map-container"
         style="width: <?= $checkoutConfig['dpd_googlemaps_width'] ?>px; height: <?= $checkoutConfig['dpd_googlemaps_height'] ?>px;"
         x-cloak
         x-show="!selectedParcelshopHtml && !error">
    </div>

    <div x-html="error" x-show="error"></div>

    <div id="dpd-connect-selected-container"
         x-cloak
         x-html="selectedParcelshopHtml"
         x-show="selectedParcelshopHtml">
    </div>
</div>
